# Generated by Django 4.0.4 on 2022-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='is_on_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='release_date',
            field=models.DateField(default='2001-09-21'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='stock_location',
            field=models.CharField(default='Ozon stock', max_length=255),
        ),
    ]
